### PR TITLE
Allow custom max value in .get

### PR DESCRIPTION
**Pull request by marcuspoehls**
This PR adds the functionality to pass a custom `max` value as limit to `limiter.get()`. This is useful for user-specific limits and does not require a different rate limiter instance for each request.

Looking forward to feedback :)

### CODE REVIEW

**Comment by Kikobeats** [comment]
Good idea, do you think could be useful customize `duration` as well?

**Comment by marcuspoehls** [comment]
Yeah, I think customizing the `duration` makes sense.

Do you want that in a second PR?

**Comment by Kikobeats** [comment]
yes please 🙂

**Comment by marcuspoehls** [comment]
PR: https://github.com/microlinkhq/async-ratelimiter/pull/2

**Pull request merged**
